### ISSUE TITLE
docker-compose方式部署如何配置自己的搭建的deepseek

### ISSUE THREAD

**Issue by zingcheng11** [weibaohui/k8m#76]
请问使用docker-compose方式部署，怎么配置自己的ai源？在yaml文件中的environment增加OPENAI_API_KEY，OPENAI_API_URL，OPENAI_MODEL等并没有生效

**Comment by weibaohui** [comment]
请参考：
```yaml
services:
  k8m:
    container_name: k8m
    image: registry.cn-hangzhou.aliyuncs.com/minik8m/k8m
    restart: always
    ports:
      - "3618:3618"
      - "3619:3619"
    environment:
      TZ: Asia/Shanghai
      ENABLE_TEMP_ADMIN: true
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: 123456
      #启用AI
      ENABLE_AI: true
      #关闭内置大模型
      USE_BUILTIN_MODEL: false
      # 设置私有化大模型
      OPENAI_API_KEY: sk-xxxxxxxx
      OPENAI_API_URL: https://api.siliconflow.cn/v1
      OPENAI_MODEL: Qwen/Qwen2.5-7B-Instruct
    volumes:
      - ./data:/app/data
```
